### ISSUE TITLE
Build error related to SSSOM export

### ISSUE THREAD

**Issue by bgyori** [biopragmatics/biomappings#87]
See https://github.com/biopragmatics/biomappings/runs/6136744213?check_suite_focus=true
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.12/x64/bin/biomappings", line 33, in <module>
    sys.exit(load_entry_point('biomappings', 'console_scripts', 'biomappings')())
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/runner/work/biomappings/biomappings/src/biomappings/cli.py", line 46, in update
    ctx.invoke(sssom)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/work/biomappings/biomappings/src/biomappings/export_sssom.py", line 99, in sssom
    msdf = from_sssom_dataframe(df, prefix_map=prefix_map, meta=META)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/sssom/parsers.py", line [253](https://github.com/biopragmatics/biomappings/runs/6136744213?check_suite_focus=true#step:4:253), in from_sssom_dataframe
    mlist.append(_prepare_mapping(Mapping(**mdict)))
  File "<string>", line 41, in __init__
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/sssom/sssom_datamodel.py", line 373, in __post_init__
    self.match_type = [
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/sssom/sssom_datamodel.py", line 374, in <listcomp>
    v if isinstance(v, MatchTypeEnum) else MatchTypeEnum(v)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/linkml_runtime/utils/enumerations.py", line 52, in __init__
    raise ValueError(f"Unknown {self.__class__.__name__} enumeration code: {key}")
ValueError: Unknown MatchTypeEnum enumeration code: LexicalEquivalenceMatch
```

**Comment by cthoyt** [comment]
This happened because the SSSOM standard got updated. I'll look in to how to fix these annotations
